version: "3"

services:
  postgres:
    image: postgres:13.4
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: testdb
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - "./postgres:/docker-entrypoint-initdb.d"
    restart: always
    hostname: postgres
    user: root